dist: trusty

branches:
  - master
  - develop

language: php
php:
  - '7.1'

services:
  - mysql
  - redis-server

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'CREATE DATABASE `biz-base-test` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci'
  - composer install

addons:
  sonarcloud:
    organization: "benzuo-stock"
    token:
      secure: $SONAR_TOKEN

script:
  - phpunit --coverage-clover=reports/phpunit.coverage.xml
  - sonar-scanner

cache:
  directories:
    - $HOME/.composer/cache


