dist: trusty

branches:
  - master
  - develop

language: php
php:
  - '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE `biz-base-test` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci'
  - composer install

addons:
  sonarcloud:
    organization: "benzuo-stock"
    token:
      secure: $SONAR_TOKEN

script:
  - phpunit --coverage-xml=report
  - sonar-scanner

cache:
  directories:
    - $HOME/.composer/cache


